### ISSUE TITLE
Toolchain issues

### ISSUE THREAD

**Issue by dakejahl** [mmcuavqgc/qgroundcontrol#1]
Which version of Qt should be used? I am attempting to compile for Android using Qt 5.12.7 on Ubuntu 18.04 and am getting a bunch of errors. Is this the official repository for the MMC Etlas Mobile GCS? 

Also, which version of QGroundControl is this forked from?

**Comment by anewyee** [comment]
Qt5.11.1 For android armv7,GCC 4.9,sdk version 25.2.5,NDK 14.1,jdk1.8

![image](https://user-images.githubusercontent.com/20177799/87756573-bc89e200-c83b-11ea-8d81-33720537bb81.png)
![image](https://user-images.githubusercontent.com/20177799/87756578-c01d6900-c83b-11ea-8ec3-b27bb9817a0a.png)
